# Welcome to Jekyll!

port: 8800
title: Awesome Site
description: Jekyll Dual-UI @ionic/core@8 x Bootstrap@5.3 Boilerplate.
baseurl: "/jekyll-dual-ui"
url: ""

# Markdown settings
markdown: kramdown

permalink: :title

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - dotenv

plugins_dir: _plugins

# Firebase - Load from environment variables
api_key: "<%= ENV['api_key'] %>"
auth_domain: "<%= ENV['auth_domain'] %>"
project_id: "<%= ENV['project_id'] %>"
database_url: "<%= ENV['database_url'] %>"
storage_bucket: "<%= ENV['storage_bucket'] %>"
sender_id: "<%= ENV['sender_id'] %>"
app_id: "<%= ENV['app_id'] %>"
measure_id: "<%= ENV['measure_id'] %>"
